/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_samples_fd_DetectionBasedTracker */

extern "C"
{
    JNIEXPORT jstring JNICALL
    Java_com_v7idea_landdetecttest_MainActivity_stringFromJNI(
            JNIEnv* env,
            jobject /* this */);

//for demo

JNIEXPORT jobject JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_yellowToWhite(
        JNIEnv *env, jclass, jobject bitmap);

JNIEXPORT jobject JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_grayscale(
        JNIEnv *env, jclass, jobject bitmap);

JNIEXPORT jobject JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_gaussianBlur(
        JNIEnv *env, jclass, jobject bitmap);

JNIEXPORT jobject JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_autoCanny(
        JNIEnv *env, jclass, jobject bitmap);

JNIEXPORT jobject JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_regionOfInterest(
        JNIEnv *env, jclass, jobject bitmap);

JNIEXPORT jobject JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_houghLines(
        JNIEnv *env, jclass, jobject bitmap);

//for demo

JNIEXPORT jobject JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_testFunction(
        JNIEnv *env, jclass, jobject bitmap);

JNIEXPORT jobject JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_byteArrayToMat(
        JNIEnv *env, jclass, jint imageWidth, jint imageHeight, jbyteArray bitmapByteArray);

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_detectLane(
        JNIEnv *env, jobject obj, jint srcWidth, jint srcHeight,
        jobject srcBuffer, jobject dstSurface);

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_setROILeftUpX(
        JNIEnv *env, jobject obj, jint leftUpX);

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_setROILeftUpY(
        JNIEnv *env, jobject obj, jint leftUpY);

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_setROILeftDownX(
        JNIEnv *env, jobject obj, jint leftDownX);

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_setROILeftDownY(
        JNIEnv *env, jobject obj, jint leftDownY);


JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_setROIRightUpX(
        JNIEnv *env, jobject obj, jint rightUpX);

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_setROIRightUpY(
        JNIEnv *env, jobject obj, jint rightUpY);

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_setROIRightDownX(
        JNIEnv *env, jobject obj, jint rightDownX);

JNIEXPORT void JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_setROIRightDownY(
        JNIEnv *env, jobject obj, jint rightDownY);


//計算所需時間

JNIEXPORT jlong JNICALL Java_org_opencv_samples_facedetect_OpenCVWrapper_getBitmapToMatTime(
        JNIEnv *env, jobject obj);

//long long BitmapToMatTime  = 0;
//long long YellowToWhiteTime = 0;
//long long grayScaleTime = 0;
//long long gaussianBlurTime = 0;
//long long medianTime = 0;
//long long autoCannyTime = 0;
//long long regionOfInterestTime = 0;
//long long HoughLinesPTime = 0;
//long long extrapolateTime = 0;
//long long houghLinesTime = 0;
//long long weightedImgTime = 0;
//long long RGB2RGBAImgTime = 0;
//long long createBitmapTime = 0;

//計算所需時間


}

